# Generated by Django 2.2.1 on 2019-12-17 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='match.Team'),
        ),
        migrations.AddField(
            model_name='teammatchpoint',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Match'),
        ),
        migrations.AddField(
            model_name='teammatchpoint',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Team'),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Match'),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='club_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.State'),
        ),
        migrations.AddField(
            model_name='team',
            name='player',
            field=models.ManyToManyField(db_table='TeamPlayer', related_name='teamplayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Address'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(db_table='TeamMatch', related_name='teams', to='match.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_team', to='match.Team'),
        ),
    ]
